copy/y dn1.yh-crlf.off ..\off\dn1.yh.off
copy/y dn1.yh-crlf.off ..\off\dn1.yh.off
copy/y dn1.yh-crlf.off ..\off\dn1.yh.off
copy/y dn1.yh-crlf.off ..\off\dn1.yh.off
copy/y dn1.yh-crlf.off ..\off\dn1.yh.off
copy/y dn2.yh-crlf.off ..\off\dn2.yh.off
copy/y dn3.yh-crlf.off ..\off\dn3.yh.off
copy/y mn1.yh-crlf.off ..\off\mn1.yh.off
copy/y mn2.yh-crlf.off ..\off\mn2.yh.off
copy/y mn3.yh-crlf.off ..\off\mn3.yh.off
copy/y sn1.yh-crlf.off ..\off\sn1.yh.off
copy/y sn2.yh-crlf.off ..\off\sn2.yh.off
copy/y sn3.yh-crlf.off ..\off\sn3.yh.off
copy/y sn4.yh-crlf.off ..\off\sn4.yh.off
copy/y sn5.yh-crlf.off ..\off\sn5.yh.off
copy/y an1.yh-crlf.off ..\off\an1.yh.off
copy/y an2.yh-crlf.off ..\off\an2.yh.off
copy/y an3.yh-crlf.off ..\off\an3.yh.off
copy/y an4.yh-crlf.off ..\off\an4.yh.off
copy/y an5.yh-crlf.off ..\off\an5.yh.off
copy/y an6.yh-crlf.off ..\off\an6.yh.off
copy/y an7.yh-crlf.off ..\off\an7.yh.off
copy/y an8.yh-crlf.off ..\off\an8.yh.off
copy/y an9.yh-crlf.off ..\off\an9.yh.off
copy/y an10.yh-crlf.off ..\off\an10.yh.off
copy/y an11.yh-crlf.off ..\off\an11.yh.off
